language: node_js
node_js:
  - '5.10'
script: bash ./deploy.sh
env:
  global:
    - ENCRYPTION_LABEL: 95017743069c
    - COMMIT_AUTHOR_EMAIL: yaroslav0507@gmail.com
branches:
  only:
    - master
cache:
  directories:
    - node_modules